project:
  type: website
  output-dir: docs


website:
  title: "Ben Townsend"
  navbar:
    right:
      - text: About Me
        href: aboutme.qmd
      - text: Blog
        href: blog.qmd
      - text: Data Resources
        href: dataresources.qmd
      - icon: github
        href: https://github.com/bentowns
      - icon: linkedin
        href: https://www.linkedin.com/in/ben-townsend-871913134?original_referer=https%3A%2F%2Fwww.google.com%2F
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

